[package]
name = "harness-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
harness-openai-codex-auth = { path = "../openai-codex-auth" }
harness-openai-codex-model = { path = "../openai-codex-model" }
harness-session-log = { path = "../harness-session-log" }

[dev-dependencies]
proptest = "=1.11.0"

[[bin]]
name = "harness"
path = "src/main.rs"
